### ISSUE TITLE
count() method is missing $quoteId parameter

### ISSUE THREAD

**Issue by redelschaap** [SEOshop/API-PHP-Client#10]
The `WebshopappApiResourceQuotesPaymentmethods::count()` method is missing the `$quoteId` parameter. Without that parameter it's not possible to count the payment methods for that quote. Also the `$params` parameter seems mandatory, but I guess it's there for consistency / future features.

``` php
/**
 * @param int   $quoteId
 * @param array $params
 *
 * @return int
 * @throws WebshopappApiException
 */
public function count( $quoteId, $params = array() ) {
    return $this->client->read( 'quotes/' . $quoteId . '/paymentmethods/count', $params );
}
```

**Comment by jeroenvisser101** [comment]
Hi @redelschaap, I'll ask @michielrensen to take a look at this when he's back from holiday! Thanks for submitting.
