### ISSUE TITLE
Use an autoloader instead of preloading all classes

### ISSUE THREAD

**Issue by redelschaap** [SEOshop/API-PHP-Client#11]
I think it's a good idea to use this API client with an autoloader. On each request over 6800 lines of code are initialized and when the `WebshopappApiClient` class is loaded at least 98 extra classes are loaded.

When using an autoloader and one or more namespaces and each class having it's own file, only 300 - 400 lines of code and 2 - 4 classes are loaded when making an API call. I can adjust the client to work with an autoloader, optionally included with a simple auto loader for those who don't work with an autoloader in their project yet.

**Comment by michielrensen** [comment]
@redelschaap you can install the client using composer (see readme)

**Comment by michielrensen** [comment]
@redelschaap I comnented too quick. You are right, such an improvement is useful. The client is generated and this was (at the time the easiest way to distribute the file). As we're moving towards a newer version, I'm not sure it's feasible to do so. We'll discuss it nevertheless.

**Comment by redelschaap** [comment]
I can do it for you if you want. Just let me know.

**Comment by jeroenvisser101** [comment]
@redelschaap as you might've seen already, we introduced a new version of our backoffice, and with that, also a new API. Since that API needs a client, we will definitely keep this in mind. Thanks for the feedback, sorry for the late reply.

**Comment by redelschaap** [comment]
No problem! Any idea when the new API and the new client will be available?

**Comment by jeroenvisser101** [comment]
Well, we're still working really hard on getting all the bugs out, so it'll be somewhere in 2016. We'll announce it officially on the blogs, and in the partner-mailing.

**Comment by redelschaap** [comment]
Great! Let me know when you need help testing the new API.

**Comment by jeroenvisser101** [comment]
@redelschaap I'll pass your name on!

**Comment by jeroenvisser101** [comment]
@redelschaap can you maybe send your details to jeroen.visser [at] lightspeedhq.com. I'll make sure you are on the list. As for the date, it'll probably be only late-2016, but at least you'll be one of the first to try it :)
