### ISSUE TITLE
Generator sources?

### ISSUE THREAD

**Issue by stroborobo** [SEOshop/API-PHP-Client#13]
Hi SEOshop.

> We love contributions, but please note that the API client is generated

Are the sources for that generator open source? I was thinking about generating an API client for a different language using the spec, if I can get my hands on it. I know about the `/resources.json`, but that doesn't contain any information about the objects, only URLs, filters and other meta stuff.

**Comment by jeroenvisser101** [comment]
Hi @stroborobo, no, it's not, sadly. It uses our API's source to determine which resources there are, and I don't think it's possible for us to make it open-source. However, since we're working really hard on our new backoffice, which includes a new API, we might consider doing this for our new API.

Thanks for your input, and I'm sorry for the late reply!

**Comment by stroborobo** [comment]
Looking forward to it, thanks! :)

**Comment by jeroenvisser101** [comment]
@stroborobo It's quite amazing, really, but I can't give more details just yet. If you want, I can pass your details on to the person that will conduct the testing. Although the testing probably will take place in late-2016, we can put you on the list :)

**Comment by stroborobo** [comment]
I guess we partners will get some kind of testing access anyway, won't we? No need for some special treatment I guess :)

But since we're talking already, it would be great if the new API could be more type safe. The current one is a little painful to use sometimes in statically types languages since there are a few places where values might be false even though they aren't boolean.

**Comment by jeroenvisser101** [comment]
@stroborobo I think you'll be more satisfied with the new one :)
