### ISSUE TITLE
Unable to finish a checkout

### ISSUE THREAD

**Issue by Edwin-Luijten** [SEOshop/API-PHP-Client#24]
I am unable to finish a checkout, the documentation tells you to do ```<?php $api->checkouts->get($checkout_id);``` while the curl request is a POST to a totally different endpoint.

So, i tried this method ```$this->client->checkoutsOrder->create($checkout_id, null);``` but this gives me an exception with invalid payload. The fields parameter is required but have no clue what to set the fields to.

The curl request works tough: ```curl -X POST https://api.webshopapp.com/en/checkouts/{id}/order.json -u {key}:{secret}```

It seems that **sendRequest** requires a value, even tough some post endpoints apparently don't require fields

**Comment by TimBloembergen** [comment]
Hi Edwin,

I just replied on the email you have send to our support staff. Right now a work-around is for example to send an empty comment as the payload to finish the order.

**Comment by Edwin-Luijten** [comment]
Cool, I already see there is a pull request. I already applied your above suggestion.
