### ISSUE TITLE
Unknown or inactive language

### ISSUE THREAD

**Issue by VIEWSION** [SEOshop/API-PHP-Client#26]
Hello,

Is there a way to get the available API language(s) if I don't know it? Unfortunately I did not store the language for all installed apps to our database on installation....

Best,
Matthias

**Comment by Donny5300** [comment]
The $apiLanguage is the language(s) that the webshop has.

`public function __construct( $apiServer, $apiKey, $apiSecret, $apiLanguage, array $config = [] )`

Small example: 

```
<?php

    $client = new WebshopApiClient( 'server', 'ApiKey', 'ApiSecret', 'ShopLanguage' );

    // ['nl', 'en', 'de', 'fr']
    foreach ($client->languages->get() as $language) {
        // Setting the language will retrieve all the items with translated details if available
        $client->setLanguage($language['code']);
    }
```

**Comment by VIEWSION** [comment]
Hey... sorry - I asked too vaguely. The Api Client/Call itself needs a language (ShopLanguage)... if it is set wrong or left empty, the call fails. So - what to do if you don't know the right API language? Trial & Error? Not really the best practice, no?

**Comment by Donny5300** [comment]
When a user installs a app, there is a language available (if im correct `$_GET['language']`). You should store that language somewhere and use it in your ApiClient.

**Comment by VIEWSION** [comment]
As I mentioned in my opening question... I forgot to store this in the beginning... so if there is no other way, I need to change this manually in my DB, right?

**Comment by Donny5300** [comment]
Thats correct. Unless your 100% sure that the language is always the same.
