### ISSUE TITLE
App / Account API 

### ISSUE THREAD

**Issue by VIEWSION** [SEOshop/API-PHP-Client#27]
Hello,
are there plans for extending the API or maybe an extra API to manage the app itself? I mean getting and settings informations about the app installation, the client payments, the invoicing, appstore content etc.. ?

Best,
Matthias

**Comment by TimBloembergen** [comment]
Hi Matthias,

There are currently no plans for these options. We have setup the partner portal to manage these kind of settings.
Perhaps in the future but not on short term.
