### ISSUE TITLE
1.9.0 release not working

### ISSUE THREAD

**Issue by sleenen** [SEOshop/API-PHP-Client#32]
I noticed you just released 1.9.0, however, when I try to retrieve shop information, I get back `null` response. 
When I downgrade to 1.8.0 it works fine. 
I went as far as checking the responseBody when doing the request. It gives back a string there, which includes headers, then tries to json_decode that. Which won't work...

**Comment by robertolightspeed** [comment]
Which version of PHP are you using @sleenen?
Also, could you paste here the exact call you are using to retrieve the shop information?

**Comment by robertolightspeed** [comment]
@sleenen after some digging we release that we had a bug indeed. A fix was deployed and you can get the new version `v1.9.1` 😇
